### PR TITLE
fix: add missing fields, fix up array type, add comments

### LINKED ISSUE #25: [BUG] `PackageJson` type missing numerous npm-documented fields
The `PackageJson` type is missing the following fields (documented on 
https://docs.npmjs.com/cli/v10/configuring-npm/package-json):
- ~~`config`~~
- ~~`cpu`~~
- `funding`
- ~~`homepage`~~
- ~~`optionalDependencies`~~
- ~~`os`~~
- `overrides`
- `peerDependenciesMeta`
- `workspaces`

[edit: strike-through fields added in #29]

### PR DESCRIPTION
**Pull request by broofa**
Making the following changes:

1. Add missing fields:
  * `funding`
  * `licenses` (deprecated)
  * `overrides`
  * `peerDependenciesMeta`
  * `workspaces`
2. Allow mixed object/string entries in `contributors`
3. Misc. comment cleanup

## References
*  Fixes #25

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -71,56 +95,59 @@ export interface PackageJSON {
...
-  bugs?: Omit<Contact, 'name'>
+  _hasShrinkwrap?: boolean
+  _id: string
+  _nodeVersion?: string // optional (ref: not defined in uuid@1.4.0)
+  _npmUser?: Contact
+  _npmVersion: string
   author?: Contact
-  // ref: Record type found in uuid@1.4.1 et al
-  browser?: Record<string, string>
+  browser?: Record<string, string> // ref: Record type found in uuid@1.4.1 et al
```
Comment (styfle) [inline types/index.d.ts:141]:
```suggestion
  browser?: string | Record<string, string> // ref: Record type found in uuid@1.4.1 et al
```

I believe this can also be a string

https://gist.github.com/defunctzombie/4339901/49493836fb873ddaa4b8a7aa0ef2352119f69211#spec

**Comment by broofa** [comment]
Ugh. Fixture tests failing... looking into it.

**Comment by broofa** [comment]
Fuck me... CI tests were failing because [`tap#matchSnapshot()` is sensitive to key-iteration order.](https://github.com/tapjs/tapjs/issues/555).

Quick fix was to `npm run snap` to regenerate fixtures.  *Actual* fix was to sort fixture keys alphabetically.

File: types/index.d.ts [hunk 2]
```diff
@@ -9,18 +10,41 @@ interface Signature {
...
 }
 
+// https://docs.npmjs.com/cli/v10/configuring-npm/package-json#funding
+interface Funding {
+  type: string
+  url: string
+}
+
+// https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides
+interface Override {
```
Comment (reggi) [inline types/index.d.ts:27]: @broofa Overrides here can be recursive according to the docs:

> Keys can be nested to any arbitrary length. To override foo only when it's a child of bar and only when bar is a child of baz:

```
{
  "overrides": {
    "baz": {
      "bar": {
        "foo": "1.0.0"
      }
    }
  }
}
```

```suggestion
interface Override {
  [moduleName: string]: string | Override
}
```

**Comment by reggi** [comment]
Thanks a bunch for the changes! I found one issue with overrides!

File: types/index.d.ts (hunk 2 above)
Comment (broofa) [reply types/index.d.ts]: Fixed.  Also renamed `Override` -> `Overrides` for consistency with `package#dependencies` property.

**Review by reggi — APPROVED** [review]
